### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by MoysesAz** [reserved1/personal-bill#1]
https://github.com/reserved1/personal-bill/blob/1214d116ddecc7f78ad5b48d1efeac42ea98f435/personal-bill/functions.swift#L11-L41

Usar uma função func "printBeautify (_ object: inout Bill)" dentro da  func printBeautify (_ array: inout Array<Bill>) para reúso.

**Comment by reserved1** [comment]
Valeu, ta alterado.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/74558455/160895857-dfed05dd-ba43-4831-b7ca-9a87b3880742.png">
