### ISSUE TITLE
Edna Moda: Nada de comentários!

### ISSUE THREAD

**Issue by Robsonmxms** [reserved1/personal-bill#2]
https://github.com/reserved1/personal-bill/blob/de8bd78caa1db445b661fe8fb17ef0d5e4648197/personal-bill/functions.swift#L43-L45

Se você precisa de comentários para explicar suas variáveis/funções, elas não estão nomeadas adequadamente, ou, no caso de funções, estão fazendo mais do que uma única coisa (que deve ser a origem de seu nome). Portanto, isto não segue os padrões de Clean Code, o que pode prejudicar a refatoração e/ou entendimento de outros Devs.

**Comment by reserved1** [comment]
Vou ficar atento a isso nos próximos testes, e modificar alguns nomes para corrigir problemas de semântica.
