### ISSUE TITLE
Code Suggestion

### ISSUE THREAD

**Issue by joaoipiraja** [reserved1/personal-bill#5]
Here's some suggestions for your code :)

- [ ]  Use [VNBarcodeObservation](https://developer.apple.com/documentation/vision/vnbarcodeobservation) to get info of barcode by camera
💡 Resources:
https://developer.apple.com/videos/play/wwdc2021/10041/
https://www.hackingwithswift.com/example-code/media/how-to-scan-a-barcode
https://benoitpasquier.com/webcam-utility-app-macos-swiftui/

**Comment by reserved1** [comment]
Ty Joao, 
This program specifically has a limitation of being command line only, but I will remember to use your suggestion when trying to update it to an application version.
